
general {
    # grace for 10 min, totally 20 min until authentication is required.
    lock_cmd = pidof hyprlock || hyprlock --grace 600  
    before_sleep_cmd = playerctl pause; loginctl lock-session
    # after_sleep_cmd = hyprctl dispatch dpms on
    # lock_cmd = notify-send "lock!"          # dbus/sysd lock command (loginctl lock-session)
}


# lock screen 10 min
listener {
    timeout = 600 
    on-timeout = loginctl lock-session
}

# screen dark at 15 min
listener {
    timeout = 900                               # 15 min.
    on-timeout = brightnessctl -s set 10      # set monitor backlight to minimum, avoid 0 on OLED monitor.
    on-resume = brightnessctl -r                 # monitor backlight restore.
}

# turn off screen
listener {
    timeout = 1500 # 25 min.
    on-timeout = hyprctl dispatch dpms off 
    on-resume = hyprctl dispatch dpms on && brightnessctl -r
}

listener {
    timeout = 1800 # 30 min.
    on-timeout = systemctl suspend
}


# listener {
#     timeout = 60
#     on-timeout = ~/.config/hypr/scripts/brb.sh
#     on-resume = ~/.config/hypr/scripts/brb-resume.sh
# }

